### ISSUE TITLE
Panic Button - Plugin to disable all profiles on press

### ISSUE THREAD

**Issue by evilC** [evilC/UCR#127]

**Comment by oneswitch** [comment]
Pretty much the same as JoyToKey's "Suspend processing of ... input (temporarily)" option.

I'm building some UCR profiles that use a lot of key-presses, including backspace and enter. I have to laboriously unblock all keyboard mapping that is set to be blocked, so that I can freely edit in UCR. Would be enormously convenient to have a method of pausing the system (much like the OneSwitch Pulse on/off feature).

**Comment by evilC** [comment]
Implemented in 0.1.4
