### ISSUE TITLE
Ghosting when too many buttons are pressed repeatedly

### ISSUE THREAD

**Issue by Snoothy** [evilC/UCR#159]
I had 3 joysticks with each 4 buttons mapped to keyboard keys. Pressing 9 buttons, 3 on each joystick, too fast will only register few of the presses. This is an issue in the game Bishi Bashi where repeat key presses are the winning condition. Does the input thread have any limitation or is this issue related to AHK?

**Comment by Snoothy** [comment]
Setting "#MaxThreads 255" seems to do the trick, but it's only running at ~90% the speed as a simple remapping script

**Comment by evilC** [comment]
What do you mean by "90% speed"?  
I would imagine that UCR will never have as low a latency between physical and virtual output as a simple remapping script (Simply because there is a longer code path between input and output) , but I see no reason why it should not be possible to be as reliable (in terms of all output always gets sent) as a simple script.
