### ISSUE TITLE
UCR 0.1.22 Failing to recognize Vjoy 2.1.8.38 dll 

### ISSUE THREAD

**Issue by ignacioherrera3** [evilC/UCR#221]
Vjoy is installed and working, but UCR fails to find the relevant registry entries, and asks to download  the latest version, wich is currently installed.

"A vJoy install was found in C:\Program Files\vJoy\, but the relevant registry entries were not found.
Please update vJoy to the latest version from 

http://vjoystick.sourceforge.net."

**Comment by evilC** [comment]
What do you have in the following registry key?  
HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{8E31F76F-74C3-47F1-9550-E041EEDC5FBB}_is1  
vJoy Feeder would work, because it does not need to look in the registry to find the DLL location.  
This is a known issue with the vJoy installer - sometimes it does not make these reg keys.  
Try uninstalling and reinstalling vJoy

**Comment by ignacioherrera3** [comment]
> What do you have in the following registry key?
> HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall{8E31F76F-74C3-47F1-9550-E041EEDC5FBB}_is1

![image](https://user-images.githubusercontent.com/47606930/52732452-de67a100-2f85-11e9-9ce4-45afcf27bca8.png)
 I have these in that registry key.
Also, thank you for your support.

**Comment by evilC** [comment]
This is what it s meant to look like.  
Notice the two selected items which I have but you don't:  
![](https://i.imgur.com/V0W4YmR.png)
