### ISSUE TITLE
Just a question.

### ISSUE THREAD

**Issue by Megatherion69** [evilC/UCR#73]
Big fan / user of your ujr program, just have a couple of questions about your new UCR program. Will it be able to bind more than 32 buttons and more than 8 axes? Do I have to add a plugin for each button / axis? UJR gui is very nice to assign many buttons / axes easily and auto config buttons to selected stick; is there going to be a similar gui for UCR? Thanks a lot for your continued work on UJR and now this new UCR, you have my gratitude for enabling me to use your programs with vjoy to be able to properly play games that have no support for multiple input devices / lousy controller support.

**Comment by Megatherion69** [comment]
Never mind, figured it all out by finally being able to use it; had to put some deadzone on my joystick and throttle quadrant otherwise UCR would crash / has stopped working...

Never mind also about the gui, once using it; it is very intuitive.

**Comment by evilC** [comment]
"Will it be able to bind more than 32 buttons and more than 8 axes?"
The limitation will remain (for now) that it can only recognize input from the first 32 buttons, 6 axes, 1 hat are for *each physical stick*.
However, the output limitations are lifted - all 128 buttons, 8 axes, 4 hats are supported as vJoy output.

"Do I have to add a plugin for each button / axis?"
Currently, yes.
"is there going to be a similar gui for UCR?"
I plan on doing something, yes, as I appreciate that adding 30 odd plugins to remap a stick is not great UX.

The crashes are due to input happening at the same time as UCR is doing other stuff. After investigation this weekend, this appears to be an AHK thing, so I am awaiting an updated version of AHK which should hopefully solve these crashes.

**Comment by evilC** [comment]
I just released a new version of UCR which should hopefully fix the access violation crashes.
Please see the [forum thread](https://autohotkey.com/boards/viewtopic.php?f=19&t=12249).
The deadzone issue you reported would have probably been because the stick was changing value even when you weren't touching it (fluctuating ever so slightly). If this new fix works, you should not need the deadzone.
